// Code generated by command: go run gen.go -out ../md5block_amd64.s -stubs ../md5block_amd64.go -pkg=md5simd. DO NOT EDIT.

//go:build !appengine && !noasm && gc

package md5simd

// Encode p to digest.
// Modified by otterIO contributors in 2026: regenerated with the maintained Avo toolchain.
//
//go:noescape
func blockScalar(dig *[4]uint32, p []byte)
